version: 1
formatters:
  journal_fmt:
    format: "%(name)s: [%(request)s] %(message)s"
  precise:
    format: "%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s"
handlers:
  journal:
    class: systemd.journal.JournalHandler
    formatter: journal_fmt
root:
  level: WARN
  handlers: [journal]
disable_existing_loggers: true
