# SPDX-FileCopyrightText: 2024 Dom Rodriguez <shymega@shymega.org.uk
#
# SPDX-License-Identifier: GPL-3.0-only

#

name: "Flake workflow"
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 23 * * *"
    - cron: "10 23 * * *"
# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: gh-ref-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update-flake:
    if: ${{ github.event_name == 'schedule' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
      - uses: cachix/install-nix-action@V27
        with:
          github_access_token: ${{ secrets.NIX_GH_ACTIONS_TOKEN }}
      - uses: nixbuild/nixbuild-action@v19
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
      - name: Update Flake lockfile
        run: nix flake update --accept-flake-config
      - name: Commit changes to lockfile
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref_name }}
          commit_message: "chore(lockfile): Update Flake lockfile"
  format-flake:
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
        with:
          github_access_token: ${{ secrets.NIX_GH_ACTIONS_TOKEN }}
      - uses: nixbuild/nixbuild-action@v19
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
      - name: Format Nix files
        run: nix fmt
      - name: Commit changes to codebase
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref_name }}
          commit_message: "chore(lint): Format Nix files"
  check-flake:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@V27
        with:
          github_access_token: ${{ secrets.NIX_GH_ACTIONS_TOKEN }}
      - uses: nixbuild/nixbuild-action@v19
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
      - name: Check Flake with Nix
        run: nix flake check --all-systems --accept-flake-config
