# SPDX-FileCopyrightText: 2024 Dom Rodriguez <shymega@shymega.org.uk
#
# SPDX-License-Identifier: GPL-3.0-only

#

name: "Flake workflow"
on:
  workflow_dispatch:
  workflow_call:
  push:
  pull_request:
# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: gh-ref-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update-flake:
    if: ${{ github.event_name == 'workflow_call' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Update Flake lockfile
        run: nix flake update --accept-flake-config
      - name: Commit changes to lockfile
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref_name }}
          commit_message: "chore(lockfile): Update Flake lockfile"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

  format-flake:
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Format Nix files
        run: nix fmt
      - name: Commit changes to codebase
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref_name }}
          commit_message: "chore(lint): Format Nix files"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

  check-flake:
    needs: [format-flake]
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check Flake with Nix
        run: nix flake check --all-systems --accept-flake-config
